field: 2f14e021-ebc7-41d3-a3ed-45a9ba0a6e6b
fieldLayouts:
  b33a9817-ed3c-4067-937e-70df6477f9f1:
    tabs:
      -
        elements:
          -
            fieldUid: a8941054-4641-48ad-8094-1ff8a4865e9e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a8941054-4641-48ad-8094-1ff8a4865e9e:
    contentColumnType: string
    fieldGroup: null
    handle: demoBlock
    instructions: ''
    name: 'Demo Block'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add a demo block'
      showSiteMenu: true
      source: null
      sources:
        - 'section:86bb3753-2427-44f9-9916-2ac12d79efba'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: block
name: Block
sortOrder: 1
