field: 1eb0ac2f-150c-4071-b0a0-cdbc98ace82e
fieldLayouts:
  a16aee75-e3c6-4b89-8ebd-d670b08018ad:
    tabs:
      -
        fields:
          3b64d0d5-85c3-4d4c-ae24-37fc64796b59:
            required: true
            sortOrder: 3
          d2ed2223-7bc8-4e0b-a214-aac9858b9f7d:
            required: false
            sortOrder: 1
          dee15867-e67b-485e-9bb4-462d27a45db3:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  3b64d0d5-85c3-4d4c-ae24-37fc64796b59:
    contentColumnType: string
    fieldGroup: null
    handle: articles
    instructions: ''
    name: Articles
    searchable: false
    settings:
      allowSelfRelations: ''
      limit: '3'
      localizeRelations: false
      selectionLabel: 'Link an Article'
      source: null
      sources:
        - 'section:2f1f0ea0-4b22-4e9d-bb51-9e1e32a94cba'
      targetSiteId: null
      validateRelatedElements: '1'
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  d2ed2223-7bc8-4e0b-a214-aac9858b9f7d:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dee15867-e67b-485e-9bb4-462d27a45db3:
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: blogCards
name: 'Blog Cards'
sortOrder: 6
