field: 1eb0ac2f-150c-4071-b0a0-cdbc98ace82e
fieldLayouts:
  d00d8afc-3e42-41dc-b8ea-91ca30334ba7:
    tabs:
      -
        elements:
          -
            fieldUid: e5a6e8ac-dc76-4be8-91f7-4b0f2ebd6aae
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d08b6d22-f84b-486c-9a56-33d72aa11ecc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d08b6d22-f84b-486c-9a56-33d72aa11ecc:
    contentColumnType: text
    fieldGroup: null
    handle: briefCopy
    instructions: 'This text will be placed below the image. Typically used to cite the image or add supplementary text.'
    name: 'Brief Copy'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e5a6e8ac-dc76-4be8-91f7-4b0f2ebd6aae:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:8b0fd7f7-2623-4a21-a578-698d8c0aef75'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8b0fd7f7-2623-4a21-a578-698d8c0aef75'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageBlock
name: Image
sortOrder: 2
