field: 1eb0ac2f-150c-4071-b0a0-cdbc98ace82e
fieldLayouts:
  4ce6f8b6-8ea1-46c5-92e7-7c9200277743:
    tabs:
      -
        fields:
          1aa2697a-4a32-496d-a3f5-f9a1e120a864:
            required: false
            sortOrder: 1
          2dd47779-aae2-4d6d-b2b7-b1cf6fd6807c:
            required: false
            sortOrder: 3
          acf69f98-cbe4-4a1e-9b48-d2d213c68a4f:
            required: false
            sortOrder: 4
          cc09c5f8-123f-4ecd-ac51-acc522445123:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  1aa2697a-4a32-496d-a3f5-f9a1e120a864:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2dd47779-aae2-4d6d-b2b7-b1cf6fd6807c:
    contentColumnType: text
    fieldGroup: null
    handle: callToActionButton
    instructions: ''
    name: 'Call to Action Button'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        6: custom
        7: email
        8: tel
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  -
                    - singles
                    - 'section:2f1f0ea0-4b22-4e9d-bb51-9e1e32a94cba'
                    - 'section:cefc4625-a115-4b71-b22d-5f6784b3aada'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  acf69f98-cbe4-4a1e-9b48-d2d213c68a4f:
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: ''
    name: 'Button Style'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Solid
            -
              - value
              - '-solid'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Outline
            -
              - value
              - '-outline'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Raised
            -
              - value
              - '-solid -raised'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cc09c5f8-123f-4ecd-ac51-acc522445123:
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 1
