field: 2e2cf186-585b-46ee-a435-b3a1737847ca
fieldLayout: a621d199-8f4b-4fd4-b954-c816aa1839d2
instructions: 'Use this banner to notify the user of important information such as a temporary closing or major change.'
name: 'Notification Banner'
