field: f697001b-d1ba-48d7-92ee-0eb172e00ac1 # Simple Copy 1
fieldLayout: ae4dd40b-e640-4115-b9c9-44a3e2ecd79b
instructions: 'This information will be displayed below the logo in the footer. Typically an address, phone number, or email address is displayed.'
name: 'Organization Details'
