fieldLayouts:
  58d45f7d-7a11-4134-b995-3928e89369c7:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: f34e1148-6584-4d08-a0e3-3d253ef838b8
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Settings
        sortOrder: 1
handle: blog
hasTitleField: false
name: Blog
section: fc636500-a798-4d09-8ecf-384a5c3239a1
sortOrder: 1
titleFormat: '{section.name|raw}'
