fieldLayouts:
  f40d69a2-6725-4334-9e07-082db17549df:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 27eb5f6d-5e7b-4401-a20a-5259596e045a # Navigation Link
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: utilityNavigaiton
hasTitleField: true
name: 'Utility Navigaiton'
section: 28b71e8e-d2dc-4c34-98c4-66e91dfbbab4 # Utility Navigaiton
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
