dateModified: 1584452560
email:
  fromEmail: codingwithkyle@gmail.com
  fromName: Boilerplate
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  225c7f29-a1ba-4281-a207-621cab6d37b7:
    name: Common
fields:
  e3ddae84-8d6f-4b5c-b636-2eaaddaa0a0f:
    contentColumnType: text
    fieldGroup: 225c7f29-a1ba-4281-a207-621cab6d37b7
    handle: alternateDescription
    instructions: 'Provide a brief description of the image or icon. This description is not visible to users and will be read to users with vision impairments or disabilities if they are utilizing screen reading technology. This field is required in order to be in compliance with the Americans with Disabilities Act.'
    name: 'Alternate Description'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f34e1148-6584-4d08-a0e3-3d253ef838b8:
    contentColumnType: text
    fieldGroup: 225c7f29-a1ba-4281-a207-621cab6d37b7
    handle: seo
    instructions: ''
    name: SEO
    searchable: false
    settings:
      description: ''
      hideSocial: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      socialImage: ''
      suffixAsPrefix: null
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
    translationKeyFormat: null
    translationMethod: none
    type: ether\seo\fields\SeoField
plugins:
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  relabel:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  splash:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
siteGroups:
  9cabe42f-fdb6-45c1-8bdd-67c0914303ff:
    name: Boilerplate
sites:
  8d2ceaf6-270f-4376-a57e-b67d74fe3518:
    baseUrl: '@rootUrl'
    handle: default
    hasUrls: true
    language: en-US
    name: Boilerplate
    primary: true
    siteGroup: 9cabe42f-fdb6-45c1-8bdd-67c0914303ff
    sortOrder: 1
system:
  edition: solo
  live: true
  name: Boilerplate
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  8b0fd7f7-2623-4a21-a578-698d8c0aef75:
    fieldLayouts:
      acae1f98-968a-47e4-9474-9929da0d5d16:
        tabs:
          -
            fields:
              e3ddae84-8d6f-4b5c-b636-2eaaddaa0a0f:
                required: true
                sortOrder: 1
            name: 'Meta Data'
            sortOrder: 1
    handle: images
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    sortOrder: 1
    type: craft\volumes\Local
    url: '@web/uploads/images'
