contentColumnType: text
fieldGroup: 225c7f29-a1ba-4281-a207-621cab6d37b7
handle: alternateDescription
instructions: 'Provide a brief description of the image or icon. This description is not visible to users and will be read to users with vision impairments or disabilities if they are utilizing screen reading technology. This field is required in order to be in compliance with the Americans with Disabilities Act.'
name: 'Alternate Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
