contentColumnType: boolean
fieldGroup: a7c4f891-d179-4c87-981e-2a644510060c # SEO
handle: noArchive
instructions: 'Do not show a "Cached" link in search results.'
name: 'No Archive'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
