contentColumnType: text
fieldGroup: 1f065b26-61c0-43d3-b24b-c350e672ae18
handle: pageBuilderResources
instructions: 'Load additional JavaScript or CSS files with this block. Provide a full URL or the name of the file within the public assets directory. Remember that JavaScript files end in the mjs format.'
name: Resources
searchable: false
settings:
  addRowLabel: 'Add a resource'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - File
            -
              - handle
              - file
            -
              - width
              - ''
            -
              - type
              - singleline
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
