contentColumnType: string
fieldGroup: 1f065b26-61c0-43d3-b24b-c350e672ae18 # Content Builder
handle: pageBuilder
instructions: ''
name: 'Content Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
