contentColumnType: string
fieldGroup: 225c7f29-a1ba-4281-a207-621cab6d37b7
handle: relatedArticles
instructions: ''
name: 'Related Articles'
searchable: false
settings:
  limit: '3'
  localizeRelations: false
  selectionLabel: 'Link Articles'
  source: null
  sources:
    - 'section:2f1f0ea0-4b22-4e9d-bb51-9e1e32a94cba'
  targetSiteId: null
  validateRelatedElements: '1'
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
