contentColumnType: string
fieldGroup: 451b931d-873f-460e-8d38-e836680cfe09 # Organization
handle: termsAndConditionsPage
instructions: ''
name: 'Terms and Conditions Page'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Link Terms and Conditions Page'
  showSiteMenu: true
  source: null
  sources:
    - 'section:cefc4625-a115-4b71-b22d-5f6784b3aada' # Pages
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
