contentColumnType: text
fieldGroup: c4451265-86dd-4e29-8607-338f8dff61d4
handle: text2
instructions: ''
name: 'Text 2'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
