contentColumnType: string(255)
fieldGroup: 451b931d-873f-460e-8d38-e836680cfe09 # Organization
handle: youtubeUrl
instructions: ''
name: 'YouTube URL'
searchable: false
settings:
  maxLength: '255'
  placeholder: ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
