fieldLayouts:
  a621d199-8f4b-4fd4-b954-c816aa1839d2:
    tabs:
      -
        elements:
          -
            fieldUid: 2e2cf186-585b-46ee-a435-b3a1737847ca # Text 1
            instructions: ''
            label: 'Notification Copy'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Tab 1'
        sortOrder: 1
handle: notifications
name: Notifications
