fieldLayouts:
  ae4dd40b-e640-4115-b9c9-44a3e2ecd79b:
    tabs:
      -
        fields:
          076e5aa3-2dc5-45c2-9f27-22086feb220d:
            required: false
            sortOrder: 4
          4e119a0c-5a69-4b77-9f74-ca2f857374ff:
            required: true
            sortOrder: 2
          9100be82-1bb3-4d25-b46c-9c05b900ad2b:
            required: false
            sortOrder: 5
          e35ca729-8355-4faf-ae53-07d599ba0a3a:
            required: true
            sortOrder: 1
          f697001b-d1ba-48d7-92ee-0eb172e00ac1:
            required: false
            sortOrder: 3
        name: Details
        sortOrder: 1
      -
        fields:
          0b71f571-ae1d-4b03-85f6-b6bb4acbb430:
            required: false
            sortOrder: 1
          0f860c17-f79b-48b7-8d1f-15243ef39303:
            required: false
            sortOrder: 3
          26b75c67-742d-41d4-94c0-cbbf13985a33:
            required: false
            sortOrder: 4
          30cd9bf0-cc40-4149-ab16-af53a8c72449:
            required: false
            sortOrder: 8
          7a0e5822-9917-4e3f-9da1-8b3368bbec1f:
            required: false
            sortOrder: 5
          81a96522-33ab-4162-a188-88892876a535:
            required: false
            sortOrder: 9
          9c8011f9-3ae4-45a4-b562-5e7beee514d2:
            required: false
            sortOrder: 7
          9cfc6137-662b-4553-8ae8-9d1176fdddcb:
            required: false
            sortOrder: 6
          c6c24fc2-32de-4289-8f1a-b2ee6d7d0d92:
            required: false
            sortOrder: 2
        name: 'Social Media'
        sortOrder: 2
handle: organizationSettings
name: 'Organization Settings'
