enableVersioning: true
handle: articles
name: Articles
propagationMethod: all
siteSettings:
  8d2ceaf6-270f-4376-a57e-b67d74fe3518:
    enabledByDefault: true
    hasUrls: true
    template: _sections/blog/article/index
    uriFormat: 'blog/{slug}'
type: channel
