enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  8d2ceaf6-270f-4376-a57e-b67d74fe3518: # Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: _sections/blog/landing/index
    uriFormat: blog
type: single
