enableVersioning: false
handle: demoBlocks
name: 'Demo Blocks'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8d2ceaf6-270f-4376-a57e-b67d74fe3518:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 4edfdf9a-542c-4329-9683-6d7566c5391f
type: structure
