enableVersioning: true
handle: headerNavigation
name: 'Header Navigation'
propagationMethod: all
siteSettings:
  8d2ceaf6-270f-4376-a57e-b67d74fe3518: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: aa94cce7-8c5f-4b20-8aa6-22825ece2c52
type: structure
