enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  8d2ceaf6-270f-4376-a57e-b67d74fe3518: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _sections/standard-page/index
    uriFormat: __home__
type: single
